[type=adoc]
:author: Tuanm

:vi-docs: https://github.com/tuandm1-at-vmo/bbb-docs/blob/master/vi.README.adoc

:mermaidjs-live: https://mermaid.live/
:mermaidjs-docs: http://mermaid.js.org/intro/
:adoc-homepage: https://asciidoctor.org/
:adoc-docs: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
:github-supports-mermaidjs: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
:gitlab-supports-mermaidjs: https://docs.gitlab.com/ee/user/markdown.html#mermaid
:vscode-homepage: https://code.visualstudio.com/
:vscode-asciidoc-extension: https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode

= bbb-docs
This is a technical documentary repository for BicycleBlueBook development teams.

{vi-docs}[Tiếng Việt]

== Tools
=== Diagrams
==== Built-in features
Almost Git providers ({github-supports-mermaidjs}[GitHub], {gitlab-supports-mermaidjs}[GitLab], etc.), we can use {mermaidjs-docs}[mermaidjs] directly as long as files saved in MarkDown formats (`.md`, `.adoc`).

==== Mermaid Live
We can use {mermaidjs-live}[this page] to draw diagrams and export them to images (prefer SVG for high quality).

=== Editors
==== Visual Studio Code
Indeed, {vscode-homepage}[Visual Studio Code] (VS Code or Code for short) is one of the most simple, light-weight (probably), well-supported editor, especifically for MarkDown typings. For {adoc-homepage}[AsciiDoctor] (AsciiDoc or adoc), we should install an extension named {vscode-asciidoc-extension}[AsciiDoc] for conviniently previewing editting documents.

== References
- AsciiDoctor syntax: {adoc-docs}[here].
- Mermaid.js syntax: {mermaidjs-docs}[here].