sequenceDiagram
    autonumber
    BBB->>BBB: tìm các bản ghi inventory có status là "Sold" và stage là "Awaiting pickup" trên CSDL
    loop các bản ghi inventory
        BBB->>eBay: lấy thông tin của item tương ứng thông qua API GetItemTransactions
        eBay-->>BBB: trả về thông tin item hoặc lỗi
        alt có lỗi xảy ra
            BBB->>BBB: cập nhật stage thành "Sold"
        else
            opt trạng thái shipment trong thông tin eBay là "PickedUp"
                BBB->>BBB: cập nhật stage thành "Sold"
            end
        end
    end
    BBB->>BBB: lưu các bản ghi được cập nhật vào CSDL