sequenceDiagram
    participant Seller
    participant BBB
    Seller->>BBB: I want to sell a bicycle via "Flat rate" shipping, here's the information!
    Note over Seller: information = bicycle info. + shipping fee + delivery provider
    BBB-->>Seller: OK, your bicycle will be listed!