sequenceDiagram
    participant Seller
    participant BBB
    Seller->>BBB: I want to sell a bicycle and please deliver it to the buyer for me, here's the information!
    Note over Seller: information = bicycle info.
    BBB-->>Seller: You have to pay a little fee to deliver the shipment!
    Seller-->>BBB: Okay, no problemo!
    BBB-->>Seller: Your bicycle will be listed!